---
title: "Untitled"
author: "Крашенинникова А.А."
date: "2024-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, eval = FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
theme_set(theme_minimal())
library(ggpubr)
library(plotly)
library(rstatix)
library(ggpubr)
library(corrplot)
library(corrr)
library(factoextra)
library(pheatmap)
library(FactoMineR)
library(ggbiplot)
library(tidymodels)
library(embed)
```
1.
```{r}
LE <- readRDS('C:\\Users\\sent-\\Downloads\\Визуализация биомедицинских данных-20240115T185620Z-001\\Визуализация биомедицинских данных\\28.10.23 _ Дмитрий Серебренников\\HW 2\\life_expectancy_data.RDS')
```
2.
```{r}
str(LE)

```
```{r}
plot_ly(LE, x = ~GDP, color = ~continent, type = "box")
plot_ly(LE, x = ~GNI, color = ~continent, type = "box")
```

3.

```{r}
new_LE <- subset(LE, LE$continent == 'Africa' | LE$continent == 'Americas')
new_LE %>% 
  filter(continent == 'Africa') %>% 
  get_summary_stats(`Life expectancy`, type = "mean_sd")
new_LE %>% 
  filter(continent == 'Americas') %>% 
  get_summary_stats(`Life expectancy`, type = "mean_sd")
ggqqplot(new_LE, 
         x = "Life expectancy", facet.by = "continent")
stat.test <- new_LE %>% 
  t_test(`Life expectancy` ~ continent) %>% 
  add_xy_position(x = "continent")
stat.test
```
4.
```{r}
new_LE_1 <- LE[,-c(1:3, 23)]
new_LE_1_cor <- cor(new_LE_1)
corrplot(new_LE_1_cor, method = 'pie')
corrplot(new_LE_1_cor, type = 'upper', method = 'circle', tl.col = 'black', diag = FALSE)
```
5.

```{r}
LE_scaled <- scale(new_LE_1)
head(LE_scaled)
LE_dist <- dist(LE_scaled, 
                        method = "euclidean"
                        )
as.matrix(LE_dist)[1:6,1:6]

LE_hc <- hclust(d = LE_dist, 
                        method = "ward.D2")
fviz_dend(LE_hc, 
          cex = 0.1)
```
6
```{r}
ph_tree <- pheatmap(LE_scaled, 
         show_rownames = FALSE, 
         clustering_distance_rows = LE_dist,
         clustering_method = "ward.D2", 
         cutree_rows = 5,
         cutree_cols = length(colnames(LE_scaled)),
         angle_col = 45, 
         main = "Heatmap + treemap")


#Описание: Кластеры с парой переменных: GDP и GNI, hospital beds и suicide rate, infant и non-communicable morality, life expectancy и basic sanitation являются той группой значений, вокруг которых строяются другие "слои" кластеров. Кластер с tuberculosis tretment по dpt immunization является самым большим. GDP и GNI находятся на отдельной ветке. Также, у этой пары параметров есть значение с большим отклонением от среднего. Переменные с большим отклонением от среднего наблюдаются в параметрах tuberculosis treatment и во всех параметрах иммунизации

```
7.

```{r}
LE_PCA <- prcomp(LE_scaled)
summary(LE_PCA)
fviz_eig(LE_PCA, addlabels = T, ylim = c(0, 40))
#первы четыре переменные объясняют около 69% вариаций данных. Порог в 90% наступает только на 9 переменной, что говорит о том, что текщие данные не пригодны для РСА анализа.
```

8.

```{r}
LE_PCA_graph <- ggbiplot(LE_PCA,  groups = as.factor(LE$continent), 
         ellipse = T, 
         scale=0, alpha = 0.1) + 
  theme_minimal()

ggplotly(LE_PCA_graph)
```

9
```{r}
#Разбиение на континенты не дало содержательной информации. Non communicable morality, morality caused traffic, tuberculous treatment, rural population имеют негативную корреляцию с первыми двумя переменными. Все параметры иммунизации имеют негативную корреляцию с РС2 и позитивную - с РС1. suicide rate, gni, CDP, per capita, urban populatuin, life expectancy, basic sanitation, clean fuels - имеют позитивную корреляцию с обеими перменными. У всех остальных параметров негативная корреляция с РС1 и позитивная - с РС2

```

10

```{r}
LE_umap <- recipe(~., data = new_LE_1) %>%  
  step_normalize(all_predictors()) %>% 
  step_umap(all_predictors()) %>%   
  prep() %>% 
  juice() 
LE_umap %>%
  ggplot(aes(UMAP1, UMAP2)) + 
  geom_point(aes(color = as.character(LE$continent)), 
             alpha = 0.7, size = 2) +
  labs(color = NULL) 

#Изображение UMAP более читаемое, но менее информативное
```
11

```{r}
new_LE_12 <- new_LE_1[, -c(1:5)]
new_LE_12_scaled <- scale(new_LE_12)
new_LE_12_PCA <- prcomp(new_LE_12_scaled)
summary(new_LE_12_PCA)
fviz_eig(new_LE_12_PCA, addlabels = T, ylim = c(0, 40))

new_LE_13 <- new_LE_1[, -c(5:10)]
new_LE_13_scaled <- scale(new_LE_13)
new_LE_13_PCA <- prcomp(new_LE_13_scaled)
summary(new_LE_13_PCA)
fviz_eig(new_LE_13_PCA, addlabels = T, ylim = c(0, 40))

new_LE_14 <- new_LE_1[, -c(10:15)]
new_LE_14_scaled <- scale(new_LE_14)
new_LE_14_PCA <- prcomp(new_LE_14_scaled)
summary(new_LE_14_PCA)
fviz_eig(new_LE_14_PCA, addlabels = T, ylim = c(0, 40))

#изменения между тремя графиками в куммулятивном проценте объяснённой вариации незначительны, первые четыре переменные объясняют 73%, 70%, 76% соответственно. Однако, представление на бб-плоте изменилось. Из-за того, что убирали производные переменные, кластеризация каждый раз собиралась по-новому.

```

```{r}
new_LE_12_PCA_graph <- ggbiplot(new_LE_12_PCA,  groups = as.factor(LE$continent), 
         ellipse = T, 
         scale=0, alpha = 0.1) + 
  theme_minimal()
new_LE_12_PCA_graph

new_LE_13_PCA_graph <- ggbiplot(new_LE_13_PCA,  groups = as.factor(LE$continent), 
         ellipse = T, 
         scale=0, alpha = 0.1) + 
  theme_minimal()
new_LE_13_PCA_graph

new_LE_14_PCA_graph <- ggbiplot(new_LE_14_PCA,  groups = as.factor(LE$continent), 
         ellipse = T, 
         scale=0, alpha = 0.1) + 
  theme_minimal()
new_LE_14_PCA_graph
```

12

```{r}

LE_dum <- LE %>%
 mutate (dum_Africa = (as.integer(continent == 'Africa'))) %>%
  mutate (dum_Oceania = (as.integer(continent == 'Oceania')))

new_LE_dum <- LE_dum[,-c(1:3, 23)]

LE_dum_scaled <- scale(new_LE_dum)
LE_dum_PCA <- prcomp(LE_dum_scaled)


LE_dum_PCA_graph <- ggbiplot(LE_dum_PCA,  groups = as.factor(LE$continent), 
         ellipse = T, 
         scale=0, alpha = 0.1) + 
  theme_minimal()

ggplotly(LE_dum_PCA_graph)
fviz_eig(LE_dum_PCA, addlabels = T, ylim = c(0, 40))

#Добавление дамми-колонок сместило порог в 90% на 10 переменную, в отличие от графика в чанке 7.
```

